const SET_USER_INFO = "SET_USER_INFO";
const SET_DATE = "SET_DATE";
const SET_NOTIFICATIONS = "SET_NOTIFICATIONS";
const MARK_NOTIFICATION_READ = "MARK_NOTIFICATION_READ";
const MARK_ALL_NOTIFICATIONS_READ = "MARK_ALL_NOTIFICATIONS_READ";

export {
  SET_USER_INFO,
  SET_DATE,
  SET_NOTIFICATIONS,
  MARK_NOTIFICATION_READ,
  MARK_ALL_NOTIFICATIONS_READ,
};
